<html lang="en">

<head>
    <title>Product</title>
</head>

<body>


<?php

/**
 * @var \SmartOSC\Article\Block\Display $block
 */

echo $block->sayHello();

?>

<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 30px;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        /*background-color: #dddddd;*/
    }

    .post-id {
        width: 2%
    }

    .post-name {
        width: 30%
    }

    .detail {
        padding-right: 50px;
    }

</style>

<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Title</th>
        <th></th>

    </tr>
    <?php
    foreach ($block->getPostCollection() as $key => $article) {
        echo '<tr>
                    <td>' . $article['article_id'] . ' </td>
                   
                    <td>' . $article['title'] . '  </td>
                    
        <td>       <a href = "http://localhost/mageno2/article/index/articledetail?id=<?php echo $post[\'article_id\'];?>">Article Detail</a></td>                   
                  </tr>';
    }
    ?>
</table>

</body>
</html>
